### ISSUE TITLE
Ongoing Task List

### ISSUE THREAD

**Issue by Kexanone** [ArmaAchilles/ZGM_Achilles_Collection#1]
### Changes
- [x] Respawn Time: Set default to 6 sec; Remove 1 sec option.
- [x] R3F logistics enabled by default.
- [x] Lower size of the images to reduce file size.
### Fixes
- [x] Players are not added to Zeus automatically.
- [x] Debug console in object attributes is not accessible for Admins.
- [ ] ~Factory credit adjustment module does not work.~
- [ ] ~QS Marker system: Does not work properly with revive.~
- [x] Revive System: Drag actions disappeared; Revive is not possible at all.
- [x] Revive System: _doKill undefined in certain cases.
- [ ] ~R3F Logistics: Can't send back the vehicle.~
### Features
- [ ] ~Create Factory: Vehicle type specific (e.g. planes, tanks, ...)~
- [x] Revive System: Optional bloodloss timer.
- [x] Revive System: Add bleeding (spawn blood pools)
- [x] Revive System: Add support that allows AI to revive
